-- Run this once in Supabase Dashboard -> SQL Editor for the portfolio project.

create table if not exists public.requests (
  id text primary key,
  name text not null,
  email text not null,
  type text not null,
  budget text,
  "desc" text,
  status text not null default 'pending'
    check (status in ('pending', 'reviewed', 'accepted', 'declined')),
  date date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  request_id text references public.requests(id) on delete set null,
  name text not null,
  role text,
  text text not null,
  rating smallint not null check (rating between 1 and 5),
  created_at timestamptz not null default now()
);

create index if not exists testimonials_created_at_idx
  on public.testimonials (created_at desc);

alter table public.requests enable row level security;
alter table public.testimonials enable row level security;

create policy "Public can read requests"
  on public.requests for select to anon using (true);
create policy "Public can submit requests"
  on public.requests for insert to anon with check (true);
create policy "Public can update request status"
  on public.requests for update to anon using (true) with check (true);

create policy "Public can read testimonials"
  on public.testimonials for select to anon using (true);
create policy "Public can submit testimonials"
  on public.testimonials for insert to anon with check (true);

alter publication supabase_realtime add table public.requests, public.testimonials;
